### PR TITLE
fix outofbounds and add jbang option

### PR DESCRIPTION
**Pull request by maxandersen**
fix out of bounds bug that happens when text is less than a 1000 characters + add a `summarizer.java` you can just run using jbang and not have to deal with all the other flags nor even clone this repo to run inference with pure java.

after this you can do `jbang doit@mariofusco/site-summarizer` or directly using `jbang https://github.com/mariofucso/site-summarizer/blob/main/summarize.java`

you can try it using my branch with or `jbang doit@maxandersen/site-summarizer/jbang` or direct with `jbang https://github.com/maxandersen/site-summarizer/blob/jbang/summarize.java`

### CODE REVIEW

**Review by mariofusco — APPROVED** [review]

**Comment by mariofusco** [comment]
Really appreciated, thanks a lot.

**Comment by mariofusco** [comment]
I believe that this is not working as expected. Launching it with Jbang:

`jbang summarize.java https://www.infoq.com/articles/native-java-quarkus/`

I get the following result:

```
mario@mario-ThinkPad-P1-Gen-5:~/workspace/site-summarizer$ jbang summarize.java https://www.infoq.com/articles/native-java-quarkus/
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-12-02 14:14:00,703 INFO  [io.quarkus] (main) quarkus 999-SNAPSHOT on JVM (powered by Quarkus 3.16.4) started in 0.412s. Listening on: http://0.0.0.0:8080
2024-12-02 14:14:00,708 INFO  [io.quarkus] (main) Profile prod activated. 
2024-12-02 14:14:00,708 INFO  [io.quarkus] (main) Installed features: [cdi, langchain4j, langchain4j-jlama, qute, rest, smallrye-context-propagation, smallrye-openapi, vertx]
2024-12-02 14:14:02,560 INFO  [org.mfu.sit.SiteSummarizer] (main) Site crawl took 1845 ms
2024-12-02 14:14:02,563 INFO  [org.mfu.sit.SiteSummarizer] (main) Text extraction took 3 ms
2024-12-02 14:14:02,563 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 17749 characters long
2024-12-02 14:14:02,574 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 16749 characters long
2024-12-02 14:14:02,574 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 15749 characters long
2024-12-02 14:14:02,575 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 14749 characters long
2024-12-02 14:14:02,575 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 13749 characters long
2024-12-02 14:14:02,575 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 12749 characters long
2024-12-02 14:14:02,575 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 11749 characters long
2024-12-02 14:14:02,575 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 10749 characters long
2024-12-02 14:14:02,575 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 9749 characters long
2024-12-02 14:14:02,576 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 8749 characters long
2024-12-02 14:14:02,576 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 7749 characters long
2024-12-02 14:14:02,576 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 6749 characters long
2024-12-02 14:14:02,576 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 5749 characters long
2024-12-02 14:14:02,576 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 4749 characters long
2024-12-02 14:14:02,576 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 3749 characters long
2024-12-02 14:14:02,576 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 2749 characters long
2024-12-02 14:14:02,577 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 1749 characters long
2024-12-02 14:14:02,577 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 749 characters long
This article is part of the article series " Native Compilation&nbsp;Boosts Java ". You can subscribe to receive notifications about new articles in this series via RSS Java dominates enterprise applications. But in the cloud, Java is more expensive than some competitors. Native compilation with GraalVM makes Java in the cloud cheaper: It creates applications that start much faster and use less memory. So native compilation raises many questions for all Java users: How does native Java change development? When should we switch to native Java? When should we not? And what framework should we use for native Java? This series will provide answers to these questions. What is Kubernetes Native Java? "[They] could run 3 times denser deployments 
---
Site summarization done in 1876 ms
```

while launching the jar on the same article with

`java -jar --enable-preview --enable-native-access=ALL-UNNAMED --add-modules jdk.incubator.vector target/quarkus-app/quarkus-run.jar https://www.infoq.com/articles/native-java-quarkus/`

I get a much better outcome:

```
mario@mario-ThinkPad-P1-Gen-5:~/workspace/site-summarizer$ java -jar --enable-preview --enable-native-access=ALL-UNNAMED --add-modules jdk.incubator.vector target/quarkus-app/quarkus-run.jar https://www.infoq.com/articles/native-java-quarkus/
WARNING: Using incubator modules: jdk.incubator.vector
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-12-02 14:07:17,483 INFO  [io.quarkus] (main) site-summarizer 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.16.4) started in 0.433s. Listening on: http://0.0.0.0:8080
2024-12-02 14:07:17,486 INFO  [io.quarkus] (main) Profile prod activated. 
2024-12-02 14:07:17,486 INFO  [io.quarkus] (main) Installed features: [cdi, langchain4j, langchain4j-jlama, qute, rest, smallrye-context-propagation, smallrye-openapi, vertx]
2024-12-02 14:07:19,401 INFO  [org.mfu.sit.SiteSummarizer] (main) Site crawl took 1909 ms
2024-12-02 14:07:19,407 INFO  [org.mfu.sit.SiteSummarizer] (main) Text extraction took 5 ms
2024-12-02 14:07:19,408 INFO  [org.mfu.sit.SiteSummarizer] (main) Summarizing content 17749 characters long
2024-12-02 14:07:20,082 INFO  [com.git.tja.jla.ten.ope.TensorOperationsProvider] (main) Using Native SIMD Operations (OffHeap)
2024-12-02 14:07:20,089 INFO  [com.git.tja.jla.mod.AbstractModel] (main) Model type = Q4, Working memory type = F32, Quantized memory type = I8
The text you provided is a summary of the Kubernetes Native Java series, which is part of the "Native Compilations Boosts Java" article series. The series aims to provide answers to questions about native compilation, such as how to use native Java, when to switch to native Java, and what framework to use.

The text also mentions the following key points:

* Native compilation with GraalVM makes Java in the cloud cheaper.
* Native compilation raises many questions for all Java users, such as how to use native Java, when to switch to native Java, and what framework to use.
* The series will provide answers to these questions.

Overall, the text provides an overview of the Kubernetes Native Java series and its goals, highlighting the importance of native compilation in the cloud and the need for answers to specific questions about native Java.

Here is a summary of the key points:

* Native compilation with GraalVM makes Java in the cloud cheaper.
* Native compilation raises many questions for all Java users, such as how to use native Java, when to switch to native Java, and what framework to use.
* The series will provide answers to these questions.

I hope this summary is helpful. Let me know if you have any further questions or if there's anything else I can help with.
---
Site summarization done in 55534 ms
```

I'm still trying to understand what's going wrong.

**Comment by mariofusco** [comment]
@maxandersen When I launch it with jbang I see that this exception is thrown many times, but I still have no idea why. Any clue?

```
java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:233)
        at io.quarkus.qute.TemplateInstanceBase.data(TemplateInstanceBase.java:45)
        at io.quarkiverse.langchain4j.QuarkusPromptTemplateFactory$QuteTemplate.render(QuarkusPromptTemplateFactory.java:67)
        at dev.langchain4j.model.input.PromptTemplate.apply(PromptTemplate.java:102)
        at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.prepareSystemMessage(AiServiceMethodImplementationSupport.java:592)
        at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.doImplement(AiServiceMethodImplementationSupport.java:149)
        at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.implement(AiServiceMethodImplementationSupport.java:131)
        at org.mfusco.sitesummarizer.SummarizerAiService$$QuarkusImpl.summarize(Unknown Source)
        at org.mfusco.sitesummarizer.SiteSummarizer.summarizeContent(SiteSummarizer.java:30)
        at org.mfusco.sitesummarizer.SiteSummarizer.summarize(SiteSummarizer.java:23)
        at org.mfusco.sitesummarizer.SiteSummarizer_ClientProxy.summarize(Unknown Source)
        at org.mfusco.sitesummarizer.SiteSummarizerMain.run(SiteSummarizerMain.java:20)
        at org.mfusco.sitesummarizer.SiteSummarizerMain_ClientProxy.run(Unknown Source)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:143)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

Is it possible that the `SummarizerAiService` implementation isn't generated correctly?

**Comment by mariofusco** [comment]
@maxandersen Nevermind, I found the problem and fixed it with this commit https://github.com/mariofusco/site-summarizer/commit/230b5c813dfcda690d7954a2021f6d5e0212592c

I wonder why jbang requires that `@V("text")` annotation [here](https://github.com/mariofusco/site-summarizer/commit/230b5c813dfcda690d7954a2021f6d5e0212592c#diff-d2bee4ea7178e158214f7b11b7aea50922624c853aa273acb36a5a523d83cd91R18) while plain java execution can work correctly even without it. Is this expected?

/cc @cescoffier @geoand Any clue?

**Comment by geoand** [comment]
Because it's likely not passing the `-parameters` argument to `javac`

**Comment by geoand** [comment]
In projects generated by Quarkus tooling, the compiler plugin is already properly configured

**Comment by mariofusco** [comment]
@geoand ok, this makes sense, thanks a lot.

**Comment by geoand** [comment]
🙏🏽

**Pull request merged**
